[versions]
agp = "8.11.1"
androidxJunit = "1.1.5"
appcompatVersion = "1.6.1"
cardview = "1.0.0"
constraintlayoutVersion = "2.1.4"
espressoCoreVersion = "3.5.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
lottie = "6.6.7"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
materialVersion = "1.8.0"
multidex = "2.0.1"
pdfboxAndroid = "2.0.27.0"
recyclerview = "1.4.0"
tessTwo = "9.1.0"
textRecognition = "16.0.1"
playServicesMlkitTextRecognitionJapanese = "16.0.1"
playServicesMlkitTextRecognitionKorean = "16.0.1"
playServicesMlkitTextRecognitionChinese = "16.0.1"

[libraries]
appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
constraintlayout-v214 = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
espresso-core-v351 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-v115 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v180 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
pdfbox-android = { module = "com.tom-roush:pdfbox-android", version.ref = "pdfboxAndroid" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
tess-two = { module = "com.rmtheis:tess-two", version.ref = "tessTwo" }
text-recognition = { module = "com.google.mlkit:text-recognition", version.ref = "textRecognition" }
play-services-mlkit-text-recognition-japanese = { group = "com.google.android.gms", name = "play-services-mlkit-text-recognition-japanese", version.ref = "playServicesMlkitTextRecognitionJapanese" }
play-services-mlkit-text-recognition-korean = { group = "com.google.android.gms", name = "play-services-mlkit-text-recognition-korean", version.ref = "playServicesMlkitTextRecognitionKorean" }
play-services-mlkit-text-recognition-chinese = { group = "com.google.android.gms", name = "play-services-mlkit-text-recognition-chinese", version.ref = "playServicesMlkitTextRecognitionChinese" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

